- name: 1 - Configurando arquivo '/etc/hosts'
  hosts: server2 

  tasks:
  # task 1
    - name: Configuracao do arquivo /etc/hosts 
      copy:
        dest: /etc/hosts
        content: |
          127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
          ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
          192.168.206.152 server01
          192.168.206.153 server02
          192.168.206.119 server03
          192.168.206.118 server04
          192.168.206.117 server05